[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
   [plugins."io.containerd.grpc.v1.cri".containerd]
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v2"
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            SystemdCgroup = true
      [plugins."io.containerd.grpc.v1.cri".registry]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
          [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.kw01"]
            endpoint = ["https://docker.kw01"]
            [plugins."io.containerd.grpc.v1.cri".registry.configs."docker.kw01".tls]
              ca_file = "/etc/pki/ca-trust/source/anchors/registry.crt"
              cert_file = "/etc/pki/ca-trust/source/anchors/registry.crt"
              key_file = "/etc/pki/ca-trust/source/anchors/registry.key"
